<?php
// This script and data application were generated by AppGini 5.50
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/patient_visits.php");
	include("$currDir/patient_visits_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('patient_visits');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "patient_visits";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`patient_visits`.`id`" => "id",
		"IF(    CHAR_LENGTH(`patients1`.`last_name`) || CHAR_LENGTH(`patients1`.`first_name`), CONCAT_WS('',   `patients1`.`last_name`, ', ', `patients1`.`first_name`), '') /* Patient */" => "patient",
		"`patient_visits`.`type_of_visit`" => "type_of_visit",
		"`patient_visits`.`prescription`" => "prescription",
		"`patient_visits`.`diagnosis`" => "diagnosis",
		"`patient_visits`.`comments`" => "comments",
		"if(`patient_visits`.`observation_date`,date_format(`patient_visits`.`observation_date`,'%m/%d/%Y'),'')" => "observation_date",
		"TIME_FORMAT(`patient_visits`.`observation_time`, '%r')" => "observation_time"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`patient_visits`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`patient_visits`.`observation_date`',
		8 => '`patient_visits`.`observation_time`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`patient_visits`.`id`" => "id",
		"IF(    CHAR_LENGTH(`patients1`.`last_name`) || CHAR_LENGTH(`patients1`.`first_name`), CONCAT_WS('',   `patients1`.`last_name`, ', ', `patients1`.`first_name`), '') /* Patient */" => "patient",
		"`patient_visits`.`type_of_visit`" => "type_of_visit",
		"`patient_visits`.`prescription`" => "prescription",
		"`patient_visits`.`diagnosis`" => "diagnosis",
		"`patient_visits`.`comments`" => "comments",
		"if(`patient_visits`.`observation_date`,date_format(`patient_visits`.`observation_date`,'%m/%d/%Y'),'')" => "observation_date",
		"TIME_FORMAT(`patient_visits`.`observation_time`, '%r')" => "observation_time"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`patient_visits`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`patients1`.`last_name`) || CHAR_LENGTH(`patients1`.`first_name`), CONCAT_WS('',   `patients1`.`last_name`, ', ', `patients1`.`first_name`), '') /* Patient */" => "Patient",
		"`patient_visits`.`type_of_visit`" => "Type of visit",
		"`patient_visits`.`prescription`" => "Prescription",
		"`patient_visits`.`diagnosis`" => "Diagnosis",
		"`patient_visits`.`comments`" => "Comments",
		"`patient_visits`.`observation_date`" => "Observation date",
		"`patient_visits`.`observation_time`" => "Observation time"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`patient_visits`.`id`" => "id",
		"IF(    CHAR_LENGTH(`patients1`.`last_name`) || CHAR_LENGTH(`patients1`.`first_name`), CONCAT_WS('',   `patients1`.`last_name`, ', ', `patients1`.`first_name`), '') /* Patient */" => "patient",
		"`patient_visits`.`type_of_visit`" => "type_of_visit",
		"`patient_visits`.`prescription`" => "prescription",
		"`patient_visits`.`diagnosis`" => "diagnosis",
		"`patient_visits`.`comments`" => "comments",
		"if(`patient_visits`.`observation_date`,date_format(`patient_visits`.`observation_date`,'%m/%d/%Y'),'')" => "observation_date",
		"TIME_FORMAT(`patient_visits`.`observation_time`, '%r')" => "observation_time"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'patient' => 'Patient');

	$x->QueryFrom="`patient_visits` LEFT JOIN `patients` as patients1 ON `patients1`.`id`=`patient_visits`.`patient` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "patient_visits_view.php";
	$x->RedirectAfterInsert = "patient_visits_view.php?SelectedID=#ID#";
	$x->TableTitle = "Patient visits";
	$x->TableIcon = "resources/table_icons/cheque.png";
	$x->PrimaryKey = "`patient_visits`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150);
	$x->ColCaption = array("Patient", "Type of visit", "Prescription", "Diagnosis", "Comments");
	$x->ColFieldName = array('patient', 'type_of_visit', 'prescription', 'diagnosis', 'comments');
	$x->ColNumber  = array(2, 3, 4, 5, 6);

	$x->Template = 'templates/patient_visits_templateTV.html';
	$x->SelectedTemplate = 'templates/patient_visits_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `patient_visits`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='patient_visits' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `patient_visits`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='patient_visits' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`patient_visits`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: patient_visits_init
	$render=TRUE;
	if(function_exists('patient_visits_init')){
		$args=array();
		$render=patient_visits_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: patient_visits_header
	$headerCode='';
	if(function_exists('patient_visits_header')){
		$args=array();
		$headerCode=patient_visits_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: patient_visits_footer
	$footerCode='';
	if(function_exists('patient_visits_footer')){
		$args=array();
		$footerCode=patient_visits_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>